name: Deploy to workers download
on:
  push:
    branches:
      - main
    paths:
      - 'apps/worker-download/**'
      - '.github/workflows/worker-download-deployment.yml'
jobs:
   deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN_WORKERS }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "apps/worker-download/"
          # projectName: tidtu # e.g. 'my-project'
          # directory:  apps/website/dist # e.g. 'dist'
          # gitHubToken: ${{ secrets.TOKEN_GITHUB }}
