name: Deploy to workers scraping
on:
  push:
    branches:
      - main
    paths:
      - 'apps/worker-examlist/**'
      # - '.github/workflows/worker-scraping-deployment.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN_WORKERS }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "apps/worker-examlist/"
          # projectName: tidtu # e.g. 'my-project'
          # directory:  apps/website/dist # e.g. 'dist'
          # gitHubToken: ${{ secrets.TOKEN_GITHUB }}
